tag @s remove number1
tag @s remove number2
tag @s remove number3
tag @s remove number4
tag @s remove number5
tag @s remove number6
tag @s remove number7
tag @s remove number8
tag @s remove number9
tag @s remove number10
tag @s remove number11
tag @s remove number12
tag @s remove number13
tag @s remove number14
tag @s remove number15
tag @s remove number16
tag @s remove number17
tag @s remove number18
tag @s remove number19
tag @s remove number20
tag @s remove number21
tag @s remove number22
tag @s remove number23
tag @s remove number24
tag @s remove number25
tag @s remove number26
tag @s remove number27
tag @s remove number28
tag @s remove number29
tag @s remove number30
tag @s remove image1
tag @s remove image2
tag @s remove image3
tag @s remove image4
tag @s remove image5
tag @s remove image6
tag @s remove image7
tag @s remove image8
tag @s remove image9
tag @s remove image10
tag @s remove image11
tag @s remove image12
tag @s remove image13
tag @s remove image14
tag @s remove image15
tag @s remove image16
tag @s remove image17
tag @s remove image18
tag @s remove image19
tag @s remove image20
tag @s remove image21
tag @s remove image22
tag @s remove image23
tag @s remove image24
tag @s remove image25
tag @s remove image26
tag @s remove image27
tag @s remove image28
tag @s remove image29
tag @s remove image30
tag @s remove image31
tag @s remove image32
tag @s remove image33
tag @s remove image34
tag @s remove image35
tag @s remove image36
tag @s remove image37
tag @s remove image38
tag @s remove image39
tag @s remove image40
tag @s remove image41
tag @s remove image42
tag @s remove image43
tag @s remove image44
tag @s remove image45
tag @s remove image46
tag @s remove image47
tag @s remove image48
tag @s remove image49
tag @s remove image50
tag @s remove image51
tag @s remove image52
tag @s remove image53
tag @s remove image54
tag @s remove image55
tag @s remove image56
tag @s remove image57
tag @s remove image58
tag @s remove image59
tag @s remove image60
tag @s remove image61
tag @s remove image62
tag @s remove image63
tag @s remove image64
tag @s remove image65
tag @s remove image66
tag @s remove image67
tag @s remove image68
tag @s remove image69
tag @s remove image70


tag @s[scores={number=1}] add number1
tag @s[scores={number=2}] add number2
tag @s[scores={number=3}] add number3
tag @s[scores={number=4}] add number4
tag @s[scores={number=5}] add number5
tag @s[scores={number=6}] add number6
tag @s[scores={number=7}] add number7
tag @s[scores={number=8}] add number8
tag @s[scores={number=9}] add number9
tag @s[scores={number=10}] add number10
tag @s[scores={number=11}] add number11
tag @s[scores={number=12}] add number12
tag @s[scores={number=13}] add number13
tag @s[scores={number=14}] add number14
tag @s[scores={number=15}] add number15
tag @s[scores={number=16}] add number16
tag @s[scores={number=17}] add number17
tag @s[scores={number=18}] add number18
tag @s[scores={number=19}] add number19
tag @s[scores={number=20}] add number20
tag @s[scores={number=21}] add number21
tag @s[scores={number=22}] add number22
tag @s[scores={number=23}] add number23
tag @s[scores={number=24}] add number24
tag @s[scores={number=25}] add number25
tag @s[scores={number=26}] add number26
tag @s[scores={number=27}] add number27
tag @s[scores={number=28}] add number28
tag @s[scores={number=29}] add number29
tag @s[scores={number=30}] add number30
tag @s[scores={number=31}] add image1
tag @s[scores={number=32}] add image2
tag @s[scores={number=33}] add image3
tag @s[scores={number=34}] add image4
tag @s[scores={number=35}] add image5
tag @s[scores={number=36}] add image6
tag @s[scores={number=37}] add image7
tag @s[scores={number=38}] add image8
tag @s[scores={number=39}] add image9
tag @s[scores={number=40}] add image10
tag @s[scores={number=41}] add image11
tag @s[scores={number=42}] add image12
tag @s[scores={number=43}] add image13
tag @s[scores={number=44}] add image14
tag @s[scores={number=45}] add image15
tag @s[scores={number=46}] add image16
tag @s[scores={number=47}] add image17
tag @s[scores={number=48}] add image18
tag @s[scores={number=49}] add image19
tag @s[scores={number=50}] add image20
tag @s[scores={number=51}] add image21
tag @s[scores={number=52}] add image22
tag @s[scores={number=53}] add image23
tag @s[scores={number=54}] add image24
tag @s[scores={number=55}] add image25
tag @s[scores={number=56}] add image26
tag @s[scores={number=57}] add image27
tag @s[scores={number=58}] add image28
tag @s[scores={number=59}] add image29
tag @s[scores={number=60}] add image30
tag @s[scores={number=61}] add image31
tag @s[scores={number=62}] add image32
tag @s[scores={number=63}] add image33
tag @s[scores={number=64}] add image34
tag @s[scores={number=65}] add image35
tag @s[scores={number=66}] add image36
tag @s[scores={number=67}] add image37
tag @s[scores={number=68}] add image38
tag @s[scores={number=69}] add image39
tag @s[scores={number=70}] add image40
tag @s[scores={number=71}] add image41
tag @s[scores={number=72}] add image42
tag @s[scores={number=73}] add image43
tag @s[scores={number=74}] add image44
tag @s[scores={number=75}] add image45
tag @s[scores={number=76}] add image46
tag @s[scores={number=77}] add image47
tag @s[scores={number=78}] add image48
tag @s[scores={number=79}] add image49
tag @s[scores={number=80}] add image50
tag @s[scores={number=81}] add image51
tag @s[scores={number=82}] add image52
tag @s[scores={number=83}] add image53
tag @s[scores={number=84}] add image54
tag @s[scores={number=85}] add image55
tag @s[scores={number=86}] add image56
tag @s[scores={number=87}] add image57
tag @s[scores={number=88}] add image58
tag @s[scores={number=89}] add image59
tag @s[scores={number=90}] add image60
tag @s[scores={number=91}] add image61
tag @s[scores={number=92}] add image62
tag @s[scores={number=93}] add image63
tag @s[scores={number=94}] add image64
tag @s[scores={number=95}] add image65
tag @s[scores={number=96}] add image66
tag @s[scores={number=97}] add image67
tag @s[scores={number=98}] add image68
tag @s[scores={number=99}] add image69
tag @s[scores={number=100}] add image70
