tag @s remove image0
tag @s remove image1
tag @s remove image2
tag @s remove image3
tag @s remove image4
tag @s remove image5
tag @s remove image6
tag @s remove image7
tag @s remove image8
tag @s remove image9
tag @s remove image10
tag @s remove image11
tag @s remove image12
tag @s remove image13
tag @s remove image14
tag @s remove image15
tag @s remove image16
tag @s remove image17
tag @s remove image18
tag @s remove image19
tag @s remove image20
tag @s remove image21
tag @s remove image22
tag @s remove image23
tag @s remove image24
tag @s remove image25
tag @s remove image26
tag @s remove image27
tag @s remove image28
tag @s remove image29
tag @s remove image30
tag @s remove image31
tag @s remove image32
tag @s remove image33
tag @s remove image34
tag @s remove image35
tag @s remove image36
tag @s remove image37
tag @s remove image38
tag @s remove image39
tag @s remove image40
tag @s remove image41
tag @s remove image42
tag @s remove image43
tag @s remove image44
tag @s remove image45
tag @s remove image46
tag @s remove image47
tag @s remove image48
tag @s remove image49
tag @s remove image50
tag @s remove image51
tag @s remove image52
tag @s remove image53
tag @s remove image54
tag @s remove image55
tag @s remove image56
tag @s remove image57
tag @s remove image58
tag @s remove image59
tag @s remove image60
tag @s remove image61
tag @s remove image62
tag @s remove image63
tag @s remove image64
tag @s remove image65
tag @s remove image66
tag @s remove image67
tag @s remove image68
tag @s remove image69
tag @s remove image70