tag @s remove number1
tag @s remove number2
tag @s remove number3
tag @s remove number4
tag @s remove number5
tag @s remove number6
tag @s remove number7
tag @s remove number8
tag @s remove number9
tag @s remove number10
tag @s remove number11
tag @s remove number12
tag @s remove number13
tag @s remove number14
tag @s remove number15
tag @s remove number16
tag @s remove number17
tag @s remove number18
tag @s remove number19
tag @s remove number20
tag @s remove number21
tag @s remove number22
tag @s remove number23
tag @s remove number24
tag @s remove number25
tag @s remove number26
tag @s remove number27
tag @s remove number28
tag @s remove number29
tag @s remove number30
