tag @s remove speed0
tag @s remove speed1
tag @s remove speed2
tag @s remove speed3
tag @s remove speed4
tag @s remove speed5
tag @s remove speed6
tag @s remove speed7
tag @s remove speed8
tag @s remove speed9
tag @s remove speed10
tag @s remove speed11
tag @s remove speed12
tag @s remove speed13
tag @s remove speed14
tag @s remove speed15
tag @s remove speed16
tag @s remove speed17
tag @s remove speed18
tag @s remove speed19
tag @s remove speed20
tag @s remove speed21
tag @s remove speed22
tag @s remove speed23
tag @s remove speed24
tag @s remove speed25
tag @s remove speed26
tag @s remove speed27
tag @s remove speed28
tag @s remove speed29
tag @s remove speed30
tag @s remove speed31
tag @s remove speed32
tag @s remove speed33
tag @s remove speed34
tag @s remove speed35
tag @s remove speed36
tag @s remove speed37
tag @s remove speed38
tag @s remove speed39
tag @s remove speed40
tag @s remove speed41
tag @s remove speed42
tag @s remove speed43
tag @s remove speed44
tag @s remove speed45
tag @s remove speed46
tag @s remove speed47
tag @s remove speed48
tag @s remove speed49
tag @s remove speed50
tag @s remove speed51
tag @s remove speed52
tag @s remove speed53
tag @s remove speed54
tag @s remove speed55
tag @s remove speed56
tag @s remove speed57
tag @s remove speed58
tag @s remove speed59
tag @s remove speed60
tag @s remove speed61
tag @s remove speed62
tag @s remove speed63
tag @s remove speed64
tag @s remove speed65
tag @s remove speed66
tag @s remove speed67
tag @s remove speed68
tag @s remove speed69
tag @s remove speed70
tag @s remove speed71
tag @s remove speed72
tag @s remove speed73
tag @s remove speed74
tag @s remove speed75
tag @s remove speed76
tag @s remove speed77
tag @s remove speed78
tag @s remove speed79
tag @s remove speed80
tag @s remove speed81
tag @s remove speed82
tag @s remove speed83
tag @s remove speed84
tag @s remove speed85
tag @s remove speed86
tag @s remove speed87
tag @s remove speed88
tag @s remove speed89
tag @s remove speed90
tag @s remove speed91
tag @s remove speed92
tag @s remove speed93
tag @s remove speed94
tag @s remove speed95
tag @s remove speed96
tag @s remove speed97
tag @s remove speed98
tag @s remove speed99
